### ISSUE TITLE
Aucun appareil ou entité malgré connexion (gen 4)

### ISSUE THREAD

**Issue by AlexaRom** [MateoGreil/homeassistant-comwatt#14]
Bonjour,

(je suis novice sur GitHub donc désolé si je n'ai pas les codes usuels par ici).
J'ai réussi tant bien que mal à installer manuellement Comwatt sur mon Home Assistant.

J'ai une box Comwatt gen 4, la connexion a bien été établie, tout fonctionne sur le site de Comwatt et pourtant, sur Home Assistant, aucun appareil ni entité ne sont remontés donc l'interconnexion n'apporte rien en l'état.
Est-ce lié au fait que le module n'est plus fonctionnel ou un soucis de paramétrage chez moi ?

Merci par avance.
Cordialement

<img width="1508" alt="Capture_d’écran_2024-02-14_à_09_09_47" src="https://github.com/MateoGreil/homeassistant-comwatt/assets/156901577/55d50692-df40-417a-bfc1-8e546326f11a">

**Comment by AlexaRom** [comment]
Finalement ... problème déjà réglé (sans le vouloir) alors que ça fait des jours que je cherche à comprendre.

J'ai migré d'un raspberry pi 4 à un Intel NUC ce jour, juste en migrant ma sauvegarde, une fois tout relancé sur le NUC, les appareils et entité apparaissent bien aussitôt dans Comwatt ...
Seul regret : visiblement les entités ne sont pas utilisables dans l'onglet énergie donc impossible de suivre la conso du domicile dans cette section grâce aux appareils comwatt déjà installés.

Voilà, peut être que ça servira à d'autres dans le futur.
Bonne journée

**Comment by MateoGreil** [comment]
Bonjour, tu devrais avoir des entités qui finissent par "Total Energy", et qui sont bien utilisable dans l'onglet energie

**Comment by AlexaRom** [comment]
Etrangement, j'avais bien les entités disponibles pour les consommateurs mais pas pour surveiller la consommation et la production.
En retournant sur home assistant quelques heures après, ces derniers étaient cette fois disponibles ...
;)
Merci

**Comment by MateoGreil** [comment]
Ok top, je suppose que c'est simplement que ca attends d'avoir un minimum de données :)
