### ISSUE TITLE
Impossibility of choosing the solar panel production sensor for the Energy board

### ISSUE THREAD

**Issue by Eiizen** [MateoGreil/homeassistant-comwatt#15]
Hello and thanks a lot for this addon!

I don't seem to be able to indicate the right sensor for my solar production, which I think should be this one [sensor.solaire_en_autoproduction_power] but which has a POWER class and not ENERGY (to view it in the "Energy distribution" graph).

![image](https://github.com/MateoGreil/homeassistant-comwatt/assets/63253624/29881596-1cef-470f-bea7-7fdc362945be)

![image](https://github.com/MateoGreil/homeassistant-comwatt/assets/63253624/bc243fe8-0a11-4f05-a514-a469b9590f0a)

I only have these choices, but they don't seem to be the right ones?
![image](https://github.com/MateoGreil/homeassistant-comwatt/assets/63253624/df154f06-55d5-4c79-8a8b-17a19ce1ea60)

Would I need another version of [sensor.solaire_en_autoproduction_power] as well, but with an "energy" class?

Thanks

**Comment by MateoGreil** [comment]
After re-reading the request, that's the `sensor.solaire_en_autoproduction_total_energy` that you're looking for ;)
