### ISSUE TITLE
Can't install Comwatt integration

### ISSUE THREAD

**Issue by BigTh0r** [MateoGreil/homeassistant-comwatt#19]
Good morning,

First of all, thank you very much for developing this integration and for assisting with the issues. Unfortunately, I can't seem to install it.

Once I add the repository to HACS, when I try to install it, I get this message in Home Assistant:

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you are running the latest version of Home Assistant.

I've tried it several times, restarting HA and nothing. My HA is fully updated (maybe that's the problem?). I don't know if I'm doing something wrong, but I can't get it to work. If it's my fault for doing something wrong, I apologize; I'm new to Home Assistant and maybe I need to do something that I don't know.

In any case, thank you very much for the help.

**Comment by MateoGreil** [comment]
Hello!

What's your homeassistant version ? (can be seen here : https://my.home-assistant.io/redirect/info/)
What's your comwatt integration version ? (can be seen in HACS)
How have you added the comwatt integration to HACS ? Have you well added through the "personnalized repo" https://github.com/MateoGreil/homeassistant-comwatt ?

**Comment by BigTh0r** [comment]
Hi Mateo,

Mi HA version is:


   - Core2024.3.3
   - Supervisor2024.03.1
   - Operating System12.1
   - Frontend20240307.0


I added the perso repo and the comwatt integration appears but when I click
to install another browser tab is opened to confirm, when I confirm the web
comeback to my home assistant and shows that error.

My comwatt is v4

Thanks in advance.

**Comment by MateoGreil** [comment]
That's probably because you haven't fully installed it.
I think you've added the repo to the HACS correctly, but then you need to download it (download button is located at the bottom right of the screen), then reboot Home Assistant, after which you'll be able to click on "ADD INTEGRATION TO MY HA".

Apologies, it seems my 'Configuration' instructions were not entirely clear.

**Comment by BigTh0r** [comment]
Oh yes, I forgot to download it…

Thank you and I’m so sorry to waste your time.

Have a nice day :)
