### ISSUE TITLE
Add internal switch from comwatt

### ISSUE THREAD

**Issue by Fredquerty** [MateoGreil/homeassistant-comwatt#20]
Can you add the internal switch from Comwatt ? There are two internal relays inside the comwatt.
I have juste updated your last version and I can see and manage the Wifi relay, But I can't see the internal relay.

Thanks by adance
Fred

**Comment by jostaupe** [comment]
Hello Mateo,
Yes it would be a great evolution to add switch for the 2 internal relays.

Thanks by adance

JHocelyn

**Comment by MateoGreil** [comment]
Yes

That's the next improvement I think.

Thanks to raise it !

**Comment by gui34990** [comment]
Hi Mateo,
Thanks for the great work !

Just to be sure, is this about being able to control the switch to connect into the electrical cabinet, like for the water heater ? As I don't see it in hass, that would be a major enhancement :)

**Comment by MateoGreil** [comment]
Yes that's it I think,
But I didn't check yet

**Comment by MateoGreil** [comment]
Hello, 
I haven't got the internal relays to check myself.
Can you check that update : https://github.com/MateoGreil/homeassistant-comwatt/releases/tag/v0.2.1
Is this working now ?

**Comment by gui34990** [comment]
Hi 
Yes it’s working now !
Nice job thanks !!

**Comment by MateoGreil** [comment]
@Fredquerty can you confirm too before I close this issue ?

**Comment by Fredquerty** [comment]
For the moment no, I can't to update comwatt integration on HA
