### ISSUE TITLE
No switch for "remote module"

### ISSUE THREAD

**Issue by jostaupe** [MateoGreil/homeassistant-comwatt#21]
When I use electric plugs, there are three entities : Power, Total Power and the switch.
But when I add a remote module (with same functionnalities in ComWatt app) only Power and Total Power are available.

I hope the module and the plug use the same protocol and that you can fixe this quickly...

Thanks for your help and work.

**Comment by MateoGreil** [comment]
Hello

Is this the internal module ?
Is this the same issue : https://github.com/MateoGreil/homeassistant-comwatt/issues/20 ?

**Comment by jostaupe** [comment]
Hello,
Thank you for your quick answer.

No this is not the same element, if you go in the Comwatt store site, you'll see it "[Module distant de mesure et de pilotage – (https://boutique.comwatt.com/produit/module-distant-de-mesure-et-de-pilotage-gen4/).

This peace is one part of the starter pack, if you want to check it I haved already setup it and I live near Bordeaux to ;-).

**Comment by jostaupe** [comment]
Bonjour Matéo,
Comme je le disais j'habite dans le secteur de Bordeaux (Arcachon) et j'ai installé le module distant chez moi mais j'en ai également commandé 2 autres donc si je peux aider en mettant à disposition des élements. 
Ce sera avec grand plaisir !

**Comment by MateoGreil** [comment]
Hello,

Ca devrait etre bon avec la https://github.com/MateoGreil/homeassistant-comwatt/releases/tag/v0.2.1
Tu peux me confirmer que ca marche de ton coté ?

**Comment by jostaupe** [comment]
Hello Matéo,
Ca fonctionne parfaitement, j'ai bien les entités Switchs pour tous les appareils y-compris les relais internes.
Merci et bon Dimanche.
