### ISSUE TITLE
No data from Comwatt, again

### ISSUE THREAD

**Issue by jostaupe** [MateoGreil/homeassistant-comwatt#27]
Good morning,
I use the entities echange_reseau_soutirage_injection_soutirage_power and echange_reseau_soutirage_injection_injection_power to define the operation of my automation. These entities are updated in principle every 2 minutes.
Several times a day without being able to define why the updates are blocked, 5 hours yesterday afternoon, 3 hours this morning...

When this happens, the sensor consumption updates are also frozen.

If I restart HA then the sensor values becomme "unknown"

Good day

**Comment by jostaupe** [comment]
Additional information,
While the datas are inaccessible via HA, they are available on the Comwatt website or mobile app.

**Comment by gui34990** [comment]
Alors que ces derniers jours j’avais eu des interruptions de data à la fois sur HA et sur comwatt, depuis une 20aine d’heure j’ai un problème similaire au tiens: plus aucun update dans HA alors que ok sur site comwatt

**Comment by gui34990** [comment]
Pas de log particulier pour moi

**Comment by jostaupe** [comment]
Hello,
J'ai relancé le script et j'attends une erreur...

**Comment by jostaupe** [comment]
Hello,
J'ai eu un nouveau plantage mais cette fois c'était la box Comwatt qui était plantée.
Je n'avait plus de retour dans HA mais l'appli était également inopérationnelle --> le reboot de la box a réglé le pb.

Quoi qu'il en soit, j'ai réglé le pb de maniére definitive en installant des pinces de mesure de puissances localement ;-).
Ce qui me permet de fonctionner hors réseau et de pouvoir moyenner mes datas.

Le reste fonctionne parfaitement, merci encore pour ton super boulot.
