### ISSUE TITLE
Consommation électrique négative 

### ISSUE THREAD

**Issue by Bdadolle** [MateoGreil/homeassistant-comwatt#30]
Bonjour 
J'utilise l'intégration pour suivre la production de mes panneaux solaires dans Home assistant. Ça marche super bien pour la production d'électricité mais mes consommations journalières suivies dans comwatt sont négatives. 
![Screenshot_20240824-072607~2](https://github.com/user-attachments/assets/c98aa398-8a19-450c-a4ae-8cbd8a938808)
Pouvez vous m'aider sur ce sujet ?
Merci
Bruno

**Comment by MateoGreil** [comment]
Bonjour,

Est-ce que ces valeurs sont simplement inversé par rapport a votre dashboard sur comwatt ?
Ou totalement fausse ?

**Comment by Bdadolle** [comment]
> Bonjour,
> 
> Est-ce que ces valeurs sont simplement inversées par rapport à votre tableau de bord sur comwatt ? Ou totalement fausse ?

Bonsoir,
Je viens de vérifier. Dans Home assistant, a 3 h du matin, j'ai une valeur négative qui correspond à la consommation de la veille. J'ai ensuite mes consommations horaire normale et la consommation journaliere est la somme des consommations de la journée - la conso de la veille.
Exemple :
Journee du 3 septembre comwatt indique une conso journalière de 2650 Wh
Journée du 4 septembre comwatt indique une conso journalière de 3720 Wh (2090+1570+60)

Journée du 4 septembre HA indique une conso journalière de 1070 Wh (2090 +1570 + 60 - 2650)
Le - 2650 étant à 3 h du matin

Et c'est comme ça tout les jours. Les valeurs journalières négatives étant les jours ou mon chauffe eau a moins consommé que la veille.
Merci pour votre aide

**Comment by MateoGreil** [comment]
Est-ce que tu es bien sur la [derniere version](https://github.com/MateoGreil/homeassistant-comwatt/releases/tag/v0.2.1) ? 
Parce que ce bug je l'avais deja corrigé en [v0.5.1](https://github.com/MateoGreil/homeassistant-comwatt/releases/tag/v0.1.5.2) (https://github.com/MateoGreil/homeassistant-comwatt/pull/6)

**Comment by MateoGreil** [comment]
je te conseil de faire l'installation via HACS, ca te proposera les mises a jours automatiquement
